/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wjjung' at '16. 5. 27 오후 8:29' with Gradle 2.13
 *
 * @author wjjung, @date 16. 5. 27 오후 8:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
